### ISSUE TITLE
Simultaneous adc.readChannel calls return same voltage across all channels

### ISSUE THREAD

**Issue by sChakerian** [kfitzgerald/raspi-kit-ads1x15#1]
When running a single read of all channels at the same time, as part of another asynchronous function, the returned voltage in the callback returns the same value across all channels.

By adding a delay of 20ms between each call at the sampling rate of 860 SPS, I was able to get intermittent success, sometimes reading the same, sometimes reading unique voltages.

Is there a way for the asynchronous read to wait for the ADC to not be busy - to avoid the undesired result?

**Comment by kfitzgerald** [comment]
Hi @sChakerian !

Good question. Since the hardware is a serial device, it is only capable of performing a single reading at a time. Therefore, it is not possible at the hardware and interface level to read multiple channels simultaneously.

Without seeing your code, I can only wager to guess that if you're reading each channel in parallel, you are essentially re-reading the data from the device which has not updated yet. By adding a delay, you may get some of the parallel operations to fire closer to a serial pattern, which is why it intermittently works that way.

To achieve the result I think you're after, I would suggest using a high sample rate and sequentially read each channel. It won't be a simultaneous reading, but perhaps that might be sufficient for your application. At your chosen 860 SPS rate, that equates to roughly 2ms between readings, so all four channels could be read within 8ms, without factoring in serial bus data rates. The ADS1015, though only 12-bit, is capable of 3300 samples per second, making it theoretically possible to read all four channels within 2ms. 

The built-in `_read()` function of this library automatically introduces a delay after the reading based on the current SPS rate. Therefore, it should be possible to do sequential readings without worrying about performing your own delay. For example, you could do something such as this:

```js
const Async = require('async');

const readings = [];
const channels = [
  ADS1x15.channel.CHANNEL_0,
  ADS1x15.channel.CHANNEL_1,
  ADS1x15.channel.CHANNEL_2,
  ADS1x15.channel.CHANNEL_3
];

Async.eachSeries(
  channels,
  (channel, nextChannel) => {
    adc.readChannel(channel, (err, value, volts) => {
      if (!err) readings.push(value); // or volts, etc
      nextChannel(err);
  },
  (err) => {
    // All channel readings are in the `readings` array
    console.log('Channel 0:', readings[0]);
    console.log('Channel 1:', readings[1]);
    console.log('Channel 2:', readings[2]);
    console.log('Channel 3:', readings[3]);

    // DONE
  }
);
```

Also, as a side note, if you want to tweak the built-in delay, you can provide the constructor option `spsExtraDelay`, which is the number of additional milliseconds to delay after the calculated SPS frequency, which defaults to `1`ms for a smidge of safety margin. You could set this to `0` to rely solely on the SPS frequency rate or even a negative number to decrease the delay if you so choose. And if you really want to get into the weeds, you could override the `_getSPSTimeout(sps) {...}` function to return the value of your choice. 

Hope this helps!
-Kevin
